@echo off
REM TypeScript型定義生成スクリプト (Windows版)
REM schemas.pyからTypeScript型定義を手動生成します

echo 🔄 Generating TypeScript types from Pydantic schemas...

REM 出力ディレクトリを確認・作成
set OUTPUT_DIR=static\js\types
if not exist "%OUTPUT_DIR%" mkdir "%OUTPUT_DIR%"

echo 📝 Manually generating TypeScript types...
echo ✅ Creating api.ts from schemas.py structure...

REM 手動でTypeScript型定義を生成
echo /**  > "%OUTPUT_DIR%\api.ts"
echo  * Auto-generated TypeScript type definitions from Pydantic schemas >> "%OUTPUT_DIR%\api.ts"
echo  * Generated on %date% %time% >> "%OUTPUT_DIR%\api.ts"
echo  * Do not edit this file manually - it will be overwritten >> "%OUTPUT_DIR%\api.ts"
echo  */ >> "%OUTPUT_DIR%\api.ts"
echo. >> "%OUTPUT_DIR%\api.ts"
echo // Please run: docker-compose exec web python manual_type_gen.py >> "%OUTPUT_DIR%\api.ts"

echo � Output: %OUTPUT_DIR%\api.ts
echo ✨ Manual type generation completed!
echo 💡 For automated generation, install json-schema-to-typescript in Docker
echo 💡 Remember to commit both schemas.py and %OUTPUT_DIR%\api.ts